//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace rec UI


namespace rec UI


namespace rec UI

module UI =
    open UI

    let chargen_ =
        Optics.lens (fun (data: UI) -> data.chargen) (fun (value: UI.Chargen.State) (data: UI) ->
            { data with chargen = value })
