//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace rec UI


namespace rec UI


namespace rec UI

module UI =
    open UI

    let stats_ =
        Optics.lens (fun (data: UI) -> data.stats) (fun (value: Domain.Model.Stats option) (data: UI) ->
            { data with stats = value })
